// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc4fjBhOGft6Zup1T_BfMwpPFsV2V_MfY',
    appId: '1:75395771499:web:4ad32b6b67fc39e3e5d52e',
    messagingSenderId: '75395771499',
    projectId: 'mynotes-89c5e',
    authDomain: 'mynotes-89c5e.firebaseapp.com',
    storageBucket: 'mynotes-89c5e.firebasestorage.app',
    measurementId: 'G-BD0B0PL0CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5CSz51q4-69m9XexeM_1c3QumVdiYwm0',
    appId: '1:75395771499:android:3756ab361692b886e5d52e',
    messagingSenderId: '75395771499',
    projectId: 'mynotes-89c5e',
    storageBucket: 'mynotes-89c5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlPABpTXfLiBDlKhYtzfL6K9oBx7f8Gk',
    appId: '1:75395771499:ios:a6acd213b25bad0fe5d52e',
    messagingSenderId: '75395771499',
    projectId: 'mynotes-89c5e',
    storageBucket: 'mynotes-89c5e.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGlPABpTXfLiBDlKhYtzfL6K9oBx7f8Gk',
    appId: '1:75395771499:ios:a6acd213b25bad0fe5d52e',
    messagingSenderId: '75395771499',
    projectId: 'mynotes-89c5e',
    storageBucket: 'mynotes-89c5e.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc4fjBhOGft6Zup1T_BfMwpPFsV2V_MfY',
    appId: '1:75395771499:web:a0a6ca92aa39e90be5d52e',
    messagingSenderId: '75395771499',
    projectId: 'mynotes-89c5e',
    authDomain: 'mynotes-89c5e.firebaseapp.com',
    storageBucket: 'mynotes-89c5e.firebasestorage.app',
    measurementId: 'G-M5W9R102BV',
  );

}